### PR TITLE
more defence against the dark database arts

### PR DESCRIPTION
**Pull request by jadwigo**
a bit more status information and flexibility in the database layer

### CODE REVIEW

**Comment by GawainLynch** [comment]
LGTM... Except that code comment... Do you mean that you can have fields in the **form** that are not in the table?

Either way, attempting to merge from 37,000 feet above the ocean!

**Comment by GawainLynch** [comment]
iPad says no...

**Comment by jadwigo** [comment]
you can have fields in de database that are not a form field

so your form has:
name
email
message

and your db has:
id (auto increment id)
datetime (sql now)
name
email
message
status (default new, feedback, done)

have a nice flight :)

**Comment by GawainLynch** [comment]
Yes, that does work now (on MySQL and PostgreSQL at least) for me in production… Either way, certainly not debating the validity of the PR… They're always welcome from you :grin: :+1:

**Pull request merged**
