### PR TITLE
Hotfix Symfony Form Events Fix

### PR DESCRIPTION
**Pull request by Raistlfiren**
- Updated Symfony Form events to use the proper dispatcher when dispatching events
- Updated documentation on how Bolt wraps Symfony form events

### CODE REVIEW

**Comment by Raistlfiren** [comment]
Should address - https://github.com/bolt/boltforms/issues/244

**Comment by rossriley** [comment]
Nice work, the code looks good, I'm just gonna test it on a couple of real installs to make sure nothing goes wrong and then we'll get it merged probably tomorrow.

**Comment by dadaxr** [comment]
hello @rossriley  ! It seems this PR has never been merged into previous version (4.3), only into master branch. Merging at least in 4.3 seems ok no ?

**Comment by BenjaminTappnad** [comment]
hello @rossriley, as @dadaxr noticed, it's still not merged into the 4.3. Is it possible for you do do it? 
Thanks

**Comment by dadaxr** [comment]
ping @bobdenotter  on that topic :) a merge on 4.3 would be usefull and avoid us from hacking files

**Comment by bobdenotter** [comment]
@dadaxr Is it possible for you to make a new PR with these changes to the `4.2` branch? If so, i'll happily merge it in, and tag a new version. :-)

**Comment by dadaxr** [comment]
@bobdenotter here we go ;) 

https://github.com/bolt/boltforms/pull/304

**Pull request merged**
